# Generated by Django 3.0.4 on 2020-04-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricator',
            name='categories',
        ),
    ]
