# Generated by Django 3.0.4 on 2020-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_auto_20200409_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
